const quest = [
  {
    name: "Session 0",
    date: "17th July 2018",
    party: ["Artiti Baumk", "Belrim Bennar", "Hieronymus Botch", "Orthon Anatole", "Tieron Malathrar", "Varic"],
    location: "The Marisberg Tavern",
    author: "N/A",
    content: `<h2>Content to be added</h2>`
  },
  {
    name: "Session 1",
    date: "18th July 2018",
    party: ["Artiti Baumk", "Hieronymus Botch", "Orthon Anatole", "Tieron Malathrar", "Varic"],
    location: "A museum in Marisberg",
    author: "James",
    content: `<p>The party started the session outside Corollas’ Museum in Marisberg ready to investigate  the stolen black glass. Upon arriving we learned that Belrim was not able to join us due to having a massive hangover from the previous night, so Varic had come in his place.</p>
    <p>We were led inside to start our investigation. The exhibits were all held in the basement, behind a door with both a magical and non-magical lock - though neither appeared to have been damaged/tampered with. Corollas lead us down and showed us the exhibits.</p>
    <p>Once down there, someone noticed that there was a part of the wall that appeared slightly different from the rest, almost like the mortar in that area was fresher than the others. Varic started to feel up the wall to check for any hidden buttons etc. Tieron found some water and manipulated it into a small crack in the wall, then froze the water to expand the crack. This loosened some of the bottom bricks, allowing Varic to knock some out of the way. When he done this, fresh loose dirt flowed out from behind it. Varic pushed his glaive into the dirt to see how far it reached - it appeared to be at least the length of the glaive.</p>
    <p>While this was happening, Orthon was being shown the other exhibits by Corollas. The notable exhibits were;</p>
    <ul><li>A bookshelf with a wide range of books</li>
    <li>Three sets of mannequins - two with armour, one without</li>
    <li>Architectural plans for various historic/famous buildings</li>
    <li>A dragon skull</li>
    <li>The podium where the black glass was held</li></ul>
    <p>Corollas clearly did not want to talk about the mannequin that was missing armour, but no one pressed him on it.</p>
    <p>Someone spotted a dirt footprint on the ground beside the podium that held the black glass. It appeared to be a dwarven footprint. As the party couldn’t find anything else, and the wall appeared to be completely blocked from the other side, the party started to leave the building. As they were leaving, Tieron discovers a letter on the table. It read;</p>
    <div class='note'><p>	Still one gold left.</p>
    <p>		-N</p></div>
    <p>Before Orthon left the building, he gives a donation to the museum, as Corollas had mentioned that he had been struggling to sustain it. This made Corollas pull Orthon aside and confess that he had not told the party everything. He told Orthon that he owed money to a man called Nellis, a shady dealer that ran casinos and other illicit businesses in the city. Apparently he could be found at one of his ‘establishments’, by the docks or In the tavern in the evenings. Orthon rejoined the party and relayed Corollas’ confesion.</p>
    <p>The party decided to go to investigate the area of the subterranea nearest to the museum. While searching the area, they come across a dingy bar where a few guys were gambling and one guy was completely pissed. Varic walked into the bar and announces; “We are looking for a man named Nellis.” To this all of the men in the bar look up and quickly look back to their games etc upon seeing who the announcement came from. Varic then walks up to the nearest table and puts his hands on the shoulders of two of the men and repeats; “We are looking for a man named Nellis.” this time with an intimidation check. He succeeded, but one of them said they don’t know what he’s talking about, and to piss off. The other starts walking behind the bar and opens a door slightly, calling out; “Hey boys, we got someone here lookin’ for Nellis.” The door opens and two more men come out. Both of them look identical to the first that called them out. All three of them pull out clubs from behind the bar.</p>
    <p>Upon seeing this Orthon steps in, asking for everyone to calm down. He states that they are conducting an investigation for a particular item and that they merely wish to talk to Nellis to help get more information. When they hear investigation, the three triplets get angrier, one of them asking: “Well who sent you on this investigation then?” Varic responds with “Corollas”. This pisses the three triplets off even more. Tieron then tried to cast Sleep on them, but fails on all three. When the triplets see this they jump over the bar to start a fight. However, one of them trips and is knocked prone.</p>
    <p>When the triplets jump over the bar, the party gets ready to attack, except for Orthon, who tries desperately to persuade everyone to calm down but is completely ignored. Hieronymus gets in two good punches on one of them and Artiti shoots an arrow into the triplet that was knocked prone. Varic gives the third a good punch as well, but then the two standing triplets start swinging with their clubs at Varic and Hieronymus, who each get hit once. The third then stands up and breaks off the arrow shaft that Artiti hit him with. Orthon then steps in and grapples the triplet who just stood up.</p>
    <p>As the Sleep failed, Tieron casts a spell that makes one of the triplets believe that the earth is wrapping around his feet, immobilising him. Hieronymus then goes to punch the same triplet he punched earlier, but critically misses and gets a smack from the triplet in response knocking Hieronymus unconscious. Seeing this, Varic takes out his Glaive, runs his hand across the blade, causing it to burst into blue flames in reaction to his blood. He swings at the triplet, causing serious damage. The triplet clobbers him in response, knocking Varic unconscious. The twin then swings at Orthon, breaking him out of the grasp he had on the third triplet.</p>
    <p>Orthon then punches the triplet who had just hit him and knocked Varic unconscious, to little effect. Tieron then sends a ball of lightning into the triplet who Hieronymus punched, killing him. Artiti shoots an arrow at the triplet who believes the earth is binding his feet, also killing him. Orthon then makes another punch at the last triplet, hoping to just knock him unconscious rather than have another death. The triplet shrugs it off and responds with two smacks of his club. Orthon also falls unconscious. Tieron then freezes the triplets legs - immobilizing him and Artiti finishes him off with a non-lethal shot to the knee.</p>
    <p>The remaining triplet is tied up and the unconscious members of the party are stabilised and eventually wake up again. The triplet reveals that he’s one of Nellis’ goons and that Corollas sold them a suit of armour to help pay off some of the debt he owes them. When searching the bar/bodies, some coins are found along with a note. The note read;</p>
    <div class='note'><p>Meet me under the temple</p>
    <p>	-P</p></div>
    <p>When asked who P was, the triplet said that it was likely Perin who had hired some of Nellis’ goons for some kind of heist job a couple of weeks ago. This matched up time wise with when the black glass was stolen. As the party was cleaning up and preparing to leave, the triplet said; “Tell Corollas that they won’t forget this, and more of Nellis’ men will be coming his way.” Varic then draws his glaive and cuts him in half. Shocked and disgusted at this, both Orthon and Tieron storm out of the bar, heading towards the temple.</p>
    <p>The other three start to clean up the bar and try to make it look like it was just a bar brawl that got out of hand, so that there wasn’t any connection to the party. While they are doing this, Orthon and Tieron arrive at the temple and warn the priests there of Nellis’ men being under the temple. The priests thank them for the warning and offer some potions of healing at a much reduced rate. Orthon buys two before the rest of the party meet up with them and they all take a short rest with some meat pies that Varic bought.</p>
    <p>The party then ventures into the subterranea below the temple and finds an opening to what appeared to be a large corridor that had caved in near the entrance. The party found a small tunnel (around the size of an ventilation duct) that they could just about crawl through (barely for Varic and Orthon). The tunnel let into a sewer that was only wide enough for single file. At either end of the sewer there were grates. Varic and Hieronymus went towards one and Tieron and Artiti went towards the other, with Orthon still on the other side of the small tunnel.</p>
    <p>When Varic reached the grate, 4 giant rats jumped out at him. Varic drew his glaive and went to town on them. Hieronymus tried to help with some darts but managed to instead hit Varic and completely miss. It had not been Hieron’s day. The rest of the party moved towards the commotion but due to the small space couldn’t assist Varic. Fortunately, he didn’t need it and slaughtered all four of the rats with his glaive that was burning with a blue flame. Unfortunately, both Varic and Hieron had got bitten by the giant rats.</p>
    <p>Now covered in shit and rat bites, the party found another small tunnel by the grate with the giant rats. They crawled through this tunnel and came out into what looked to be the continuation of the caved in corridor. There was a wooden door opposite the tunnel and further ahead the corridor turned left. Orthon had a look at Varic’s bite marks but he wasn’t showing any symptoms. Orthon gave him a potion of healing for the bites anyway.</p>
    <p>While the rest of the party was cleaning and/or healing up, Tieron started to peer round the turning. The corridor continued into an S bend, with a suit of steel plate armour standing at the end of the turning. Tieron started to walk towards it but triggered a trip wire, causing the armour to come to life and step towards him, sword drawn. Hearing the clattering footsteps of the armour, the rest of the party started to rush to Tieron.</p>
    <p>Tieron slows the armours movements by freezing its legs, and runs back to the corner to get out of it’s reach. The party rushes round the corner and each start smashing the armour to pieces. Hieron gets in first and throws his spear, but it misses and thunks into the wall beside the armour. Orthon then comes in and whacks it with his mace, followed up by Varic’s flaming glaive. Sparks start flying from Tieron’s hands as he grabs the armour - zapping it with his shocking grasp. While running to go grab his spear, Hieron whacks it twice with a kick and an elbow smack, though as it’s against plate armour, it doesn’t really do much…</p>
    <p>Artiti finishes the armour off with a satisfying critical smash to the helmet, ripping it off the rest of the armour and pinning the helmet to the wall behind. The armour clatters to the ground and the sword it was wielding falls out of its hands. Now that it isn’t being swung at them, the party notices that it seems to be decorated with runes of some kind. Tieron picks it up to inspect further, but the sword flies out of his hand and slashes at him. The sword then starts floating in front of the party, as if it was wielded by an invisible warrior.</p>
    <p>Orthon and Varic swing at the sword, breaking off the tip of the sword. Tieron - pissed at getting slashed at by this sword - shoots a ball of lightning into the sword, breaking it in half. Artiti throws some shit from the sewer in the area where the ‘invisible warrior’ would be, but it just flies straight through. Hieron runs at the sword and attempts to jump onto it, but the sword dodges out of the way. Orthon and Varic finish of the sword with their swings, breaking the last bit into pieces.</p>
    <p>Now that the armour was defeated, Hieron peered round the corner to the rest of the corridor. He was greeted by a crossbow bolt flying past his head. Hieron dashed back, when a surprisingly high class sounding dwarf shouted “Piss off!”. Artiti snuck up to the corner and used a small mirror to peer round the corner. Round it he saw 6 figures of many races, that had barricaded themselves with upturned tables. 5 of the men wielded crossbows, while the 6th was a well dressed dwarf who stood behind them. Hearing this, Varic stated to the group; “We are only here for the black glass, return it and there won’t be any trouble.” The dwarf responded with; “You take one step round this corner and you’re a gonna, so piss off!” To this, Varic looks at the party, picks up the chest plate of the recently smashed armour and notions to Artiti to prepare an arrow.</p>
    <p>Varic runs at full pelt towards the other side of the corridor and makes a leap to jump into cover on the other side, all while holding up the chest plate as a shield. The enemy group - shocked by this giant man jumping in front of them - instinctively loose arrows in his general direction, not prepared for this sudden appearance. Artiti responds with a deadly shot towards the dwarf in the backline, landing an arrow right between his eyes, instantly killing the dwarf. Varic sees this mid jump and smiles.</p>
    <div class='bold'><p>An arrow thunks into Varics head.</p></div>
    <p>Two more follow, getting through the gaps in the chest plate. Varic hits the ground and slides behind the cover he was aiming for - his body is limp. The party is enraged. Hieron rushes round the corner spear at the ready. The enemy are all busy trying to reload their crossbows. Hieron runs into the middle of them and jumps, stabbing one with his spear and kicking another in the face. Tieron comes round the corner and launches an electrified Chromatic orb at another, killing him. Artiti knocks another arrow and launches it into the head of another, killing him outright. Orthon runs forward and stops in front of two of them, before releasing his acid breath into two of the unready foes.</p>
    <p>With their leader and two others dead, the enemy start to panic, and try to draw their swords to defend themselves, but Hieron and Tieron were ready, with Hieron landing two heavy punches, finishing him off. Tieron casts a ray of frost to freeze an already acid burned half-elf to death. The last enemy, terrified by this show of dominance drops his sword and surrenders.</p>
    <p>Orthon runs over to Varics limp body and casts lay on hands, bringing him back from the brink of death. Varic slowly opens one eye, but finds that he can’t open the other. The arrow that hit him in the head destroyed his left eye. Belrim owes him big time for this one.</p>
    <p>The last survivor of the group is tied up while the area is searched. While searching the well dressed dwarf, a coin pouch is found. Varic opens the pouch to find 10 GP, and a small square piece of black glass. The others in the group question the survivor, who tells them that the well dressed dwarf was Perin, and that he had led them here to try and open up the door at the end of the corridor. At the end of the corridor, the was a large stone wall with intricate patterns and runes covering it, and a small slot in the middle.</p>
    <p>Varic takes the black glass out of the pouch and electricity starts to spread across the black glass from Varic’s fingers. This shocks the survivor, exclaiming “How did you do that?!” Varic ignores him and walks towards the stone wall. He inserts the black glass into the slot in the wall. The patterns and ruins start to glow and a thin opening starts to appear in the wall stretching from the ceiling to the floor along the line of the glass. This opening expands out more, opening the door to the area behind. Varic takes the glass square from the door.</p>
    <p>The area revealed to the party was the inside of a huge dome made entirely of black glass. The dome was around 100 foot in diameter and appeared to be impossibly perfect. In the center of this dome was another small dome (roughly 3 foot across), also made of black glass. The party enter the room and start inspecting the area. Varic walks towards the center dome and notices a handprint on it. Upon placing his hand there, the same electricity that spread across the black glass square starts to spread from Varic’s hand. The electricity also starts to spread from the feet of the rest of the party, slowly growing in size and brightness.</p>
    <p>Varic takes his hand away from the dome but the electricity still spreads from the handprint and everyone’s feet. It grows larger and brighter still, starting to spread up the walls/ceiling of the large dome. The party starts to back away when suddenly images start flashing up on the walls/ceiling of seemingly random scenes. Pictures of people growing older, talking, sleeping and eating. Scenes of children playing, men at work and of people dying. All of these images are flashing by too quick for anyone to take in - just about grasping the contents but no real detail.</p>
    <p>As the party are overwhelmed and confused by this sudden turn of events, something even stranger happens. Multiple godly voices start talking in unison inside of each party members head;</p>
    <div class='note'><p>Fate has chosen her daughters and sons</p>
    <p>and all but they her mercy shuns</p>
    <p>We stole the souls of half our subjects</p>
    <p>For the cycle ever twice that collects</p>
    <p>Within five Relics that power is stored</p>
    <p>Scattered in the wake of a shattered accord</p>
    <p>Betrayer, patriarch, the decaying king</p>
    <p>Against him, our relics, you must bring</p>
    <p>At the end of time lies your last stand</p>
    <p>For only you can save this land.</p></div>
    <p>As soon as the last words are spoken, a large crack appears in the ceiling above and gallons of water gush out. The door the party had come through starts to close. As the party makes to back out the room, a giant blob of water splashes down and start to rise up into a humanoid form, towering over the party at almost 15 foot tall. As the party make for the door, Orthon tries to hold the door open to make sure his companions make it through, but the force of it closing is to much for him. Although the water was getting to ankle height, the party manage to get out of the room before the door closes on the water elemental.</p>
    <p>Varic grabs the tied up survivor while the party makes for the tunnels they had originally came from. Although the door was closed, water was still leaking out of it and slowly spreading through the rest of the corridor. When the party reached the tunnel, they saw that the sewer water that once was only at ankle height, now had raised so much that the small tunnel was partially submerged, and the water was flowing by too quick to even attempt to fight.</p>
    <p>Running out of options, the party went through the wooden door opposite the small tunnel to come into a dirt tunnel with a small opening with light trickling down from above. In the center of the opening was a half buried skeleton with a raised hand, upon which was a gleaming gold ring. As Varic approached the skeleton, a mound of dirt raised up in front of him, from which a sound of vomited gravel (try to imagine that) verberated. Oddly enough, Tieron understood these sounds and could speak them himself.</p>
    <p>Tieron realised the mud mound was a mud mephit, who had said “Oi, hands off me treasure!” Tieron responded very eloquently with “I’m most sorry, we didn't mean to disturb you and we have no intention of taking your treasure. We merely wish to escape this place.” The mud mephit responded with; “Well, a’ight then, but if I see any yous going near our treasure, that’d be it for you lot, got it?”</p>
    <p>With the situation under control, the party looks up to the light source to see that there was an opening with a steel runged ladder protruding from the bottom. The bottom of the ladder however, was over 20 foot in the air. Varic put the tied up survivor down, and got in position to give someone a foot hold that he could help launch them up. Hieron, back up, then made a running jump at Varic, who launched him up and into the reach of the ladder. He Climbed up, tied a rope to the ladder and threw the end down to the party. As everyone climbed out of the pit, they looked around to discover they had just come out the well in someone’s garden...</p>`
  },
  {
    name: "Session 2",
    date: "12th August 2018",
    party: ["Artiti Baumk", "Hieronymus Botch", "Oriande Mallorn", "Orthon Anatole", "Shay Coulltree", "Tieron Malathrar", "Varic"],
    location: "A dude's garden in Marisberg",
    author: "Zac",
    content: `<p>We begin the session with the party dragging themselves out of the well and into the chill night air of an overgrown garden nestled behind an equally disused manor house.  Covered in blood and human waste the group trudged through the streets (attracting a few looks from guards and civilians alike) towards the museum of Corollas Bagridden. Along the way Varic and Orthon made a quick detour to the temple district and left the unconscious and freshly castrated (via foot) thug on the temple steps before returning to the group.</p>
    <p>Upon arrival at the small museum the party found the door ajar and heard voices from within. The group made their way down the house steps to the museum proper and saw a small gnomish woman, with jet black hair tied up in a neat pony tail and neat yet functional clothes, in an intense academic discussion with Corollas about the history of the old civilisations and prophecies. The party were both quite a sight and smell. After brief questioning Corollas assured the party that Shay (played by Rachel) could be trusted and was an academic friend from the small social circle of those interested in the history of this relatively young world.</p>
    <p>Varic presented the black glass artefact to Corollas without saying anything. Corollas was taken aback and revealed that truthfully he did not expect the party to succeed in their task. He pressed the party for details and Tieron and Orthon recounted the exploration of the sewers and the encounter with Perrin. When asked about his eye, Varic conceded that there were some confrontations with both Perrin’s men and the triplets working for Nellis. He reassured Corollas that his troubles with the gang were likely through.</p>
    <p>The party went on to explain to Corollas the events in the ruins, the strange properties of the black glass artefact and the domed chamber in which the party experienced the visions. Upon Orthon mentioning the words he heard in his head whilst in the domed chamer the group began to realise that they had all heard the same thing. Slowly, Hieronymus began to recount the words of the prophecy and the whole group joined in in reading the prophecy aloud. To the groups’ surprise, Shay joined in too.</p>
    <p>Corollas is surprised and excited. “That’s impossible. One of the most well known features of black glass is that it can’t be enchanted by any modern means. This must be looked into further.”</p>
    <p>Although Corollas was low on gold he rewarded the group with an enchanted key (1/20 chance to open any lock then breaks on success) and an eyepatch for Varic who begrudgingly accepted it. Corollas then pointed the party towards the Shade Wood as that was the origin of the black glass square the party had returned to him. This is no short treck and will be fraught with danger during the winter months. Despite this, all members of the party were keen to discover more about what this prophecy had in store for them and almost felt a pull leading them towards greater things. Shay stated that she was not to be left behind and would be coming too, provided the party took a bath.</p>
    <p>Whilst the rest of the group were scrubbing themselves in the sea, Tieron began asking around the docks in the hope of obtaining a vessel to take the group to the mainland. He discovered that only fishing vessels are venturing into the open waters from Marisberg at this time. Winter has started to take a hold of the continent and all those not protected by Oynel (god of farming and fishing) risk the wrath of Aver and Nepteri (earth gods of the wind and seas). He does however hear rumours of a specific vessel still making the short run from the town of Mondalton to Bucliff on the mainland. Tieron meets with the party over drinks and informs them of this and that we should leave in the morning in order to catch the ship before it too stops making the journey for the winter.</p>
    <p>The party enjoy some well-earned downtime, and some ran a few errands. Varic met with Gidor Firestout, his boss and owner of the tavern complex in Marisberg, and explained that he must leave but left him 20 gold in exchange for all the good will that Gidor had shown him during his stay. Varic also asked about the whereabouts of his good friend Belrim Bennar and discovered that he had left early the previous day muttering some nonsense about words in his dreams. The bar staff had assumed him drunk.</p>
    <p>Hieronymus used his new coinage to enjoy an evening in the finest bath house in the city and soak his weary body. Orthon spent some time in the temple of Uxen seeking guidance on his current path but his patron remained silent. Shay used the evening rest to start pouring through tomes from the Marisberg library that had any information on the Shade Wood, prophecies and the use of black glass by the old civilisation.</p>
    <p>The party set off in the morning led by Artiti as he had hunted in the woods and grassland surrounding Marisberg for many years and new best how to avoid the dangers that stalked the land. Despite the best efforts of Artiti to use the safer paths the party were ambushed by a seven-strong raiding party of Orcs whilst skirting a plain of shoulder height grass. The orcs were dressed in crude camouflage and wielded brutish greataxes and javelins. Hieronymus was quick into the fray and quickly felled one orc with a thrust of his spear followed by a flying knee. Shay, excited by her first ever taste of action, drew a bead on one of the brutes flanking the isolated monk and sent a bolt through the back of the creature’s head. She didn’t even see the orc hit the floor as in a flash she had dived into the cover of the long grass. The combat progressed in the party’s favour with Varic and Orthon wading in to engage with the remaining orc stupid enough to engage the party up close, Tieron putting and orc into a deep sleep and Artiti and Shay trading fire with the remaining orcs hurling javelins from the backlines.</p>
    <p>Hieronymus sensed a rout and charged the remaining cluster of orcs managing to land a few crunching strikes before being lifted off his feet by an arcing blow that sent him spiralling through the air and landing unconscious in the grass. Emboldened by seeing their party member fall the group charged forward, Varic’s flaming glaive carved one of the remaining orcs from shoulder to hip in a spray of sizzling blood and yet another of Shay’s bolts found it’s mark with a resounding thud. Before Orthon could rush to Hieronymus’ aid the Monk sprang up from the floor, bloodied and ragged but alive. Varic finished off the sleeping orc and silence fell once more.</p>
    <p>After tending to the monk’s wounds the party continued on and, through Artiti’s guidance, made good time to Mondalton. The town was sparsely populated to say the least and consisted of a small wooden palisade leading onto a cluster of small houses, a meagre looking tavern and a dock that, at the moment, contained a single ship with no sails.  The party piled into the small tavern and met the barkeep, a dwarf named Aggy (regarded by the group as a top bloke), and a slightly awkward young man who just wanted to read his book. Upon being pressed by Shay he revealed his name to be Oriande (played by Phoebe) and he was travelling on the ship in the morning.</p>
    <p>Tieron approached the ship’s captain who was busy tinkering and asked for passage on the vessel in the morning. His name was revealed to be Egridian, the captain of the only one-man ship in the world. Egridian was amazed by Tieron’s mariner past and agreed to let the party travel on the ship for free (man-crush). With their passage secured the party settled down for a long rest after a few drinks.</p>
    <p>The party made good time in the morning and met Egridian in the process of a few final checks on his vessel. The man then sealed himself in the captains cabin, grasped two strange orbs and glazed over. The ship very rapidly picked up speed and was soon travelling at a mighty speed through the waves. The party would have surely been thrown overboard by the motion of the vessel but somehow their boots felt surely planted on the deck. Egridian owns a magic boat.</p>
    <p>The first couple of hours passed with most of the party enjoying the sea breeze and the salt spray. Shay skipped from railing to railing in her excitement and even Oriande relaxed around the new faces a little to take in the rolling waves. Orthon however really did not enjoy the experience and the heavily armoured dragonborn spent a large portion of his time hanging over the rail and reacquainting himself with his breakfast.</p>
    <p>As time passed, Tieron began to notice a storm brewing in the ship’s path and called to Egridian warning him. Egridian advised holding onto something as things were going to get rough. Rain began to lash down and, even with the magic holding the ship relatively steady, the ride became notably rougher.</p>
    <p>A few minutes passed of this before Varic became aware of shapes moving alongside the boat in the water. He barely had time to shout a warning to the group and run his hand along the blade of his glaive before 10 merfolk exploded out of the water and started to drag themselves over the rails of the ship. The party started to convene in centre of the deck in a defensive formation before a large scaled creature dragged itself onto the decking beside Orthon. It wielded a wicked looking trident with coils of rope tied to one end and bared rows of needle-like teeth.</p>
    <p>Carnage broke out. Hieronymus was a dervish of fists and steel, Tieron sent a ball of crackling electricity into a nearby merfolk before bringing his arm quickly up to summon a wall of force to shatter three javelins destined for his chest and Oriande radiated invigorating holy energy before sending bolts of pure white flame hurtling at the assailants. Shay took cover behind a barrel and took pot shots at anything that moved and Artiti, seeing a group of merfolk rushing the cleric, muttered a few words and loosed an arrow that embedded itself in a merfolk’s chest before detonating in a hail of thorns and chunks of flesh. No sooner had Artiti lowered his bow the wind was taken out of him as the huge trident buried itself into his shoulder. He had no chance to cry out before he was dragged across the slippery decking and into the grasp of the huge scaled creature (a merrow). The party could only look on in horror as the creature bit down and tore a huge gash out of the left side of Artiti’s face and neck. Artiti crumbled to the floor, his ravaged face making the deck slick with blood.</p>
    <p>Orthon, upon seeing his comrade fall, raised his hammer to the sky and, with a prayer to Uxen, brought it down upon the creature’s flank. The ship shook with the sound of a thunderclap and the creature was thrown to the deck under the immense force of the blow yet somehow it began to coil and regain its posture. As it began to prepare a strike at Orthon that he planted his feet to take upon his shield, a bolt tore through it’s eye and stopped it mid-lunge. Shay darted behind the barrel again before Orthon could thank her.</p>
    <p>With the merrow fallen, the party made short work of the remaining merfolk and Oriande rushed over to aid Artiti. With a word of prayer to Pandrel as he cradled the rangers head the wounds on Artiti began to glow and knit back together. Coughing, Artiti regained consciousness and staggered to his feet away from the cleric. Touching the side of his face, he ran a finger across the scarred tissue that now remained where his ear used to be.</p>
    <p>Looting the corpses yielded a magical trident from the merrow which Varic handed to the sorcerer as he seemed the one most attuned to the sea.</p>
    <p>With the battle behind them the party looked to the horizon, and saw the outlines of buildings in the distance. Bucliff awaits.</p>

    <p class="heading">Extra Fluff</p>
    <ul class=''><li>Varic can’t believe that Gnomes exist and loves it</li>
    <li>Shay is a crossbow-wielding raptor from Jurassic Park with all that grass stealthing (#bonusactionhide)</li>
    <li>Oriande reads Twilight confirmed</li>
    <li>Artiti squished Citizen Squeaks (his mouse) when he slipped in the sewer. Press F in the chat.</li>
    <li>Tieron being able to avoid being covered in shit really made the rest of the group look bad</li>
    <li>Hieronymus and Varic shared a tender moment at the prow of the magic boat and don’t know if they should talk about it or not</li>
    <li>Belrim is on a mad bagpipe bender and was last seen mooning an ancient red dragon</li>
    <li>Orthon cured Varic’s shits before they manifested. If that isn’t bonding I don’t know what is.</li>
    <li>Calum rolls far too many 20’s and it scares me</li>
    <li>Hieronymus has a surprisingly vast knowledge of the location of many creatures testicles and how to best pop them. This includes merfolk, which he managed to pop in the last fight</li></ul>`
  },
  {
    name: "Session 3",
    date: "TBC",
    party: ["TBC"],
    location: "A magical boat on the way to Bucliff",
    author: "N/A",
    content: `<p class="heading">Session has not started yet</p>`
  }
];
