const quest = [
  {
    name: "Session 0",
    date: "17th July 2018",
    party: ["Artiti Baumk", "Belrim Bennar", "Hieronymus Botch", "Orthon Anatole", "Tieron Malathrar", "Varic"],
    location: "The Marisberg Tavern",
    content: `<h2>Content to be added</h2>`
  },
  {
    name: "Session 1",
    date: "18th July 2018",
    party: ["Artiti Baumk", "Hieronymus Botch", "Orthon Anatole", "Tieron Malathrar", "Varic"],
    location: "A museum in Marisberg",
    content: `<p>The party started the session outside Corollas’ Museum in Marisberg ready to investigate  the stolen black glass. Upon arriving we learned that Belrim was not able to join us due to having a massive hangover from the previous night, so Varic had come in his place.</p>
    <p>We were led inside to start our investigation. The exhibits were all held in the basement, behind a door with both a magical and non-magical lock - though neither appeared to have been damaged/tampered with. Corollas lead us down and showed us the exhibits.</p>
    <p>Once down there, someone noticed that there was a part of the wall that appeared slightly different from the rest, almost like the mortar in that area was fresher than the others. Varic started to feel up the wall to check for any hidden buttons etc. Tieron found some water and manipulated it into a small crack in the wall, then froze the water to expand the crack. This loosened some of the bottom bricks, allowing Varic to knock some out of the way. When he done this, fresh loose dirt flowed out from behind it. Varic pushed his glaive into the dirt to see how far it reached - it appeared to be at least the length of the glaive.</p>
    <p>While this was happening, Orthon was being shown the other exhibits by Corollas. The notable exhibits were;</p>
    <ul><li>A bookshelf with a wide range of books</li>
    <li>Three sets of mannequins - two with armour, one without</li>
    <li>Architectural plans for various historic/famous buildings</li>
    <li>A dragon skull</li>
    <li>The podium where the black glass was held</li></ul>
    <p>Corollas clearly did not want to talk about the mannequin that was missing armour, but no one pressed him on it.</p>
    <p>Someone spotted a dirt footprint on the ground beside the podium that held the black glass. It appeared to be a dwarven footprint. As the party couldn’t find anything else, and the wall appeared to be completely blocked from the other side, the party started to leave the building. As they were leaving, Tieron discovers a letter on the table. It read;</p>
    <div class='note'><p>	Still one gold left.</p>
    <p>		-N</p></div>
    <p>Before Orthon left the building, he gives a donation to the museum, as Corollas had mentioned that he had been struggling to sustain it. This made Corollas pull Orthon aside and confess that he had not told the party everything. He told Orthon that he owed money to a man called Nellis, a shady dealer that ran casinos and other illicit businesses in the city. Apparently he could be found at one of his ‘establishments’, by the docks or In the tavern in the evenings. Orthon rejoined the party and relayed Corollas’ confesion.</p>
    <p>The party decided to go to investigate the area of the subterranea nearest to the museum. While searching the area, they come across a dingy bar where a few guys were gambling and one guy was completely pissed. Varic walked into the bar and announces; “We are looking for a man named Nellis.” To this all of the men in the bar look up and quickly look back to their games etc upon seeing who the announcement came from. Varic then walks up to the nearest table and puts his hands on the shoulders of two of the men and repeats; “We are looking for a man named Nellis.” this time with an intimidation check. He succeeded, but one of them said they don’t know what he’s talking about, and to piss off. The other starts walking behind the bar and opens a door slightly, calling out; “Hey boys, we got someone here lookin’ for Nellis.” The door opens and two more men come out. Both of them look identical to the first that called them out. All three of them pull out clubs from behind the bar.</p>
    <p>Upon seeing this Orthon steps in, asking for everyone to calm down. He states that they are conducting an investigation for a particular item and that they merely wish to talk to Nellis to help get more information. When they hear investigation, the three triplets get angrier, one of them asking: “Well who sent you on this investigation then?” Varic responds with “Corollas”. This pisses the three triplets off even more. Tieron then tried to cast Sleep on them, but fails on all three. When the triplets see this they jump over the bar to start a fight. However, one of them trips and is knocked prone.</p>
    <p>When the triplets jump over the bar, the party gets ready to attack, except for Orthon, who tries desperately to persuade everyone to calm down but is completely ignored. Hieronymus gets in two good punches on one of them and Artiti shoots an arrow into the triplet that was knocked prone. Varic gives the third a good punch as well, but then the two standing triplets start swinging with their clubs at Varic and Hieronymus, who each get hit once. The third then stands up and breaks off the arrow shaft that Artiti hit him with. Orthon then steps in and grapples the triplet who just stood up.</p>
    <p>As the Sleep failed, Tieron casts a spell that makes one of the triplets believe that the earth is wrapping around his feet, immobilising him. Hieronymus then goes to punch the same triplet he punched earlier, but critically misses and gets a smack from the triplet in response knocking Hieronymus unconscious. Seeing this, Varic takes out his Glaive, runs his hand across the blade, causing it to burst into blue flames in reaction to his blood. He swings at the triplet, causing serious damage. The triplet clobbers him in response, knocking Varic unconscious. The twin then swings at Orthon, breaking him out of the grasp he had on the third triplet.</p>
    <p>Orthon then punches the triplet who had just hit him and knocked Varic unconscious, to little effect. Tieron then sends a ball of lightning into the triplet who Hieronymus punched, killing him. Artiti shoots an arrow at the triplet who believes the earth is binding his feet, also killing him. Orthon then makes another punch at the last triplet, hoping to just knock him unconscious rather than have another death. The triplet shrugs it off and responds with two smacks of his club. Orthon also falls unconscious. Tieron then freezes the triplets legs - immobilizing him and Artiti finishes him off with a non-lethal shot to the knee.</p>
    <p>The remaining triplet is tied up and the unconscious members of the party are stabilised and eventually wake up again. The triplet reveals that he’s one of Nellis’ goons and that Corollas sold them a suit of armour to help pay off some of the debt he owes them. When searching the bar/bodies, some coins are found along with a note. The note read;</p>
    <div class='note'><p>Meet me under the temple</p>
    <p>	-P</p></div>
    <p>When asked who P was, the triplet said that it was likely Perin who had hired some of Nellis’ goons for some kind of heist job a couple of weeks ago. This matched up time wise with when the black glass was stolen. As the party was cleaning up and preparing to leave, the triplet said; “Tell Corollas that they won’t forget this, and more of Nellis’ men will be coming his way.” Varic then draws his glaive and cuts him in half. Shocked and disgusted at this, both Orthon and Tieron storm out of the bar, heading towards the temple.</p>
    <p>The other three start to clean up the bar and try to make it look like it was just a bar brawl that got out of hand, so that there wasn’t any connection to the party. While they are doing this, Orthon and Tieron arrive at the temple and warn the priests there of Nellis’ men being under the temple. The priests thank them for the warning and offer some potions of healing at a much reduced rate. Orthon buys two before the rest of the party meet up with them and they all take a short rest with some meat pies that Varic bought.</p>
    <p>The party then ventures into the subterranea below the temple and finds an opening to what appeared to be a large corridor that had caved in near the entrance. The party found a small tunnel (around the size of an ventilation duct) that they could just about crawl through (barely for Varic and Orthon). The tunnel let into a sewer that was only wide enough for single file. At either end of the sewer there were grates. Varic and Hieronymus went towards one and Tieron and Artiti went towards the other, with Orthon still on the other side of the small tunnel.</p>
    <p>When Varic reached the grate, 4 giant rats jumped out at him. Varic drew his glaive and went to town on them. Hieronymus tried to help with some darts but managed to instead hit Varic and completely miss. It had not been Hieron’s day. The rest of the party moved towards the commotion but due to the small space couldn’t assist Varic. Fortunately, he didn’t need it and slaughtered all four of the rats with his glaive that was burning with a blue flame. Unfortunately, both Varic and Hieron had got bitten by the giant rats.</p>
    <p>Now covered in shit and rat bites, the party found another small tunnel by the grate with the giant rats. They crawled through this tunnel and came out into what looked to be the continuation of the caved in corridor. There was a wooden door opposite the tunnel and further ahead the corridor turned left. Orthon had a look at Varic’s bite marks but he wasn’t showing any symptoms. Orthon gave him a potion of healing for the bites anyway.</p>
    <p>While the rest of the party was cleaning and/or healing up, Tieron started to peer round the turning. The corridor continued into an S bend, with a suit of steel plate armour standing at the end of the turning. Tieron started to walk towards it but triggered a trip wire, causing the armour to come to life and step towards him, sword drawn. Hearing the clattering footsteps of the armour, the rest of the party started to rush to Tieron.</p>
    <p>Tieron slows the armours movements by freezing its legs, and runs back to the corner to get out of it’s reach. The party rushes round the corner and each start smashing the armour to pieces. Hieron gets in first and throws his spear, but it misses and thunks into the wall beside the armour. Orthon then comes in and whacks it with his mace, followed up by Varic’s flaming glaive. Sparks start flying from Tieron’s hands as he grabs the armour - zapping it with his shocking grasp. While running to go grab his spear, Hieron whacks it twice with a kick and an elbow smack, though as it’s against plate armour, it doesn’t really do much…</p>
    <p>Artiti finishes the armour off with a satisfying critical smash to the helmet, ripping it off the rest of the armour and pinning the helmet to the wall behind. The armour clatters to the ground and the sword it was wielding falls out of its hands. Now that it isn’t being swung at them, the party notices that it seems to be decorated with runes of some kind. Tieron picks it up to inspect further, but the sword flies out of his hand and slashes at him. The sword then starts floating in front of the party, as if it was wielded by an invisible warrior.</p>
    <p>Orthon and Varic swing at the sword, breaking off the tip of the sword. Tieron - pissed at getting slashed at by this sword - shoots a ball of lightning into the sword, breaking it in half. Artiti throws some shit from the sewer in the area where the ‘invisible warrior’ would be, but it just flies straight through. Hieron runs at the sword and attempts to jump onto it, but the sword dodges out of the way. Orthon and Varic finish of the sword with their swings, breaking the last bit into pieces.</p>
    <p>Now that the armour was defeated, Hieron peered round the corner to the rest of the corridor. He was greeted by a crossbow bolt flying past his head. Hieron dashed back, when a surprisingly high class sounding dwarf shouted “Piss off!”. Artiti snuck up to the corner and used a small mirror to peer round the corner. Round it he saw 6 figures of many races, that had barricaded themselves with upturned tables. 5 of the men wielded crossbows, while the 6th was a well dressed dwarf who stood behind them. Hearing this, Varic stated to the group; “We are only here for the black glass, return it and there won’t be any trouble.” The dwarf responded with; “You take one step round this corner and you’re a gonna, so piss off!” To this, Varic looks at the party, picks up the chest plate of the recently smashed armour and notions to Artiti to prepare an arrow.</p>
    <p>Varic runs at full pelt towards the other side of the corridor and makes a leap to jump into cover on the other side, all while holding up the chest plate as a shield. The enemy group - shocked by this giant man jumping in front of them - instinctively loose arrows in his general direction, not prepared for this sudden appearance. Artiti responds with a deadly shot towards the dwarf in the backline, landing an arrow right between his eyes, instantly killing the dwarf. Varic sees this mid jump and smiles.</p>
    <div class='bold'><p>An arrow thunks into Varics head.</p></div>
    <p>Two more follow, getting through the gaps in the chest plate. Varic hits the ground and slides behind the cover he was aiming for - his body is limp. The party is enraged. Hieron rushes round the corner spear at the ready. The enemy are all busy trying to reload their crossbows. Hieron runs into the middle of them and jumps, stabbing one with his spear and kicking another in the face. Tieron comes round the corner and launches an electrified Chromatic orb at another, killing him. Artiti knocks another arrow and launches it into the head of another, killing him outright. Orthon runs forward and stops in front of two of them, before releasing his acid breath into two of the unready foes.</p>
    <p>With their leader and two others dead, the enemy start to panic, and try to draw their swords to defend themselves, but Hieron and Tieron were ready, with Hieron landing two heavy punches, finishing him off. Tieron casts a ray of frost to freeze an already acid burned half-elf to death. The last enemy, terrified by this show of dominance drops his sword and surrenders.</p>
    <p>Orthon runs over to Varics limp body and casts lay on hands, bringing him back from the brink of death. Varic slowly opens one eye, but finds that he can’t open the other. The arrow that hit him in the head destroyed his left eye. Belrim owes him big time for this one.</p>
    <p>The last survivor of the group is tied up while the area is searched. While searching the well dressed dwarf, a coin pouch is found. Varic opens the pouch to find 10 GP, and a small square piece of black glass. The others in the group question the survivor, who tells them that the well dressed dwarf was Perin, and that he had led them here to try and open up the door at the end of the corridor. At the end of the corridor, the was a large stone wall with intricate patterns and runes covering it, and a small slot in the middle.</p>
    <p>Varic takes the black glass out of the pouch and electricity starts to spread across the black glass from Varic’s fingers. This shocks the survivor, exclaiming “How did you do that?!” Varic ignores him and walks towards the stone wall. He inserts the black glass into the slot in the wall. The patterns and ruins start to glow and a thin opening starts to appear in the wall stretching from the ceiling to the floor along the line of the glass. This opening expands out more, opening the door to the area behind. Varic takes the glass square from the door.</p>
    <p>The area revealed to the party was the inside of a huge dome made entirely of black glass. The dome was around 100 foot in diameter and appeared to be impossibly perfect. In the center of this dome was another small dome (roughly 3 foot across), also made of black glass. The party enter the room and start inspecting the area. Varic walks towards the center dome and notices a handprint on it. Upon placing his hand there, the same electricity that spread across the black glass square starts to spread from Varic’s hand. The electricity also starts to spread from the feet of the rest of the party, slowly growing in size and brightness.</p>
    <p>Varic takes his hand away from the dome but the electricity still spreads from the handprint and everyone’s feet. It grows larger and brighter still, starting to spread up the walls/ceiling of the large dome. The party starts to back away when suddenly images start flashing up on the walls/ceiling of seemingly random scenes. Pictures of people growing older, talking, sleeping and eating. Scenes of children playing, men at work and of people dying. All of these images are flashing by too quick for anyone to take in - just about grasping the contents but no real detail.</p>
    <p>As the party are overwhelmed and confused by this sudden turn of events, something even stranger happens. Multiple godly voices start talking in unison inside of each party members head;</p>
    <div class='note'><p>Fate has chosen her daughters and sons</p>
    <p>and all but they her mercy shuns</p>
    <p>We stole the souls of half our subjects</p>
    <p>For the cycle ever twice that collects</p>
    <p>Within five Relics that power is stored</p>
    <p>Scattered in the wake of a shattered accord</p>
    <p>Betrayer, patriarch, the decaying king</p>
    <p>Against him, our relics, you must bring</p>
    <p>At the end of time lies your last stand</p>
    <p>For only you can save this land.</p></div>
    <p>As soon as the last words are spoken, a large crack appears in the ceiling above and gallons of water gush out. The door the party had come through starts to close. As the party makes to back out the room, a giant blob of water splashes down and start to rise up into a humanoid form, towering over the party at almost 15 foot tall. As the party make for the door, Orthon tries to hold the door open to make sure his companions make it through, but the force of it closing is to much for him. Although the water was getting to ankle height, the party manage to get out of the room before the door closes on the water elemental.</p>
    <p>Varic grabs the tied up survivor while the party makes for the tunnels they had originally came from. Although the door was closed, water was still leaking out of it and slowly spreading through the rest of the corridor. When the party reached the tunnel, they saw that the sewer water that once was only at ankle height, now had raised so much that the small tunnel was partially submerged, and the water was flowing by too quick to even attempt to fight.</p>
    <p>Running out of options, the party went through the wooden door opposite the small tunnel to come into a dirt tunnel with a small opening with light trickling down from above. In the center of the opening was a half buried skeleton with a raised hand, upon which was a gleaming gold ring. As Varic approached the skeleton, a mound of dirt raised up in front of him, from which a sound of vomited gravel (try to imagine that) verberated. Oddly enough, Tieron understood these sounds and could speak them himself.</p>
    <p>Tieron realised the mud mound was a mud mephit, who had said “Oi, hands off me treasure!” Tieron responded very eloquently with “I’m most sorry, we didn't mean to disturb you and we have no intention of taking your treasure. We merely wish to escape this place.” The mud mephit responded with; “Well, a’ight then, but if I see any yous going near our treasure, that’d be it for you lot, got it?”</p>
    <p>With the situation under control, the party looks up to the light source to see that there was an opening with a steel runged ladder protruding from the bottom. The bottom of the ladder however, was over 20 foot in the air. Varic put the tied up survivor down, and got in position to give someone a foot hold that he could help launch them up. Hieron, back up, then made a running jump at Varic, who launched him up and into the reach of the ladder. He Climbed up, tied a rope to the ladder and threw the end down to the party. As everyone climbed out of the pit, they looked around to discover they had just come out the well in someone’s garden...</p>`
  },
  {
    name: "Session 2",
    date: "12th August 2018",
    party: ["TBC"],
    location: "A dude's garden in Marisberg",
    content: "<h2>To be added</h2>"
  }
];
